pages:
  image: node:14
  stage: deploy
  script:
    - npm i -g insomnia-documenter
    - mkdir public
    - insomnia-documenter --config specs.json --output public/
  artifacts:
    paths:
      - public
  only:
  - master
