pages:
  image: node:14
  stage: deploy
  script:
    - npm i -g insomnia-documenter
    - insomnia-documenter --config specs.json 
    - mkdir .result
    - cp -r * .result
    - mv .result public
  artifacts:
    paths:
      - public
  only:
  - master
