pages:
  image: node:14
  stage: deploy
  script:
    - npm i -g insomnia-documenter
    - mkdir result
    - insomnia-documenter --config specs.json --output result
    - cp -r * result
    - mkdir public
    - mv result public
  artifacts:
    paths:
      - public
  only:
  - master
